### ISSUE TITLE
JWT token renewal

### ISSUE THREAD

**Issue by lerebel103** [GoogleCloudPlatform/iot-device-sdk-embedded-c#76]
Hi all,

Is there a way to renew a JWT token with `iot-device-sdk-embedded-c` so a connection can persist please? I am seeing `IOTC_CONNECTION_RESET_BY_PEER_ERROR` once a connection hits the token expiry time, which I presume is the expected behaviour if  one doesn't renew a JWT prior to its expiry.

With reference to [Using JSON Web Tokens (JWTs)](https://cloud.google.com/iot/docs/how-tos/credentials/jwts), I can see this functionality provided for Java, Node and Python but I must be missing something as I can't find a way to do this for `iot-device-sdk-embedded-c`, other than re-creating a new connection once its breaks.

What's the correct way of renewing tokens please?

**Comment by atigyi** [comment]
Unfortunately there is no token renewal MQTT functionality without MQTT reconnection. A client must send a new MQTT CONNECT message containing a new JWT to keep connection to the IoT Core MQTT Bridge.

As I see even the [Using JSON Web Tokens (JWTs)](https://cloud.google.com/iot/docs/how-tos/credentials/jwts#required_claims) is a bit contradictory: "You can prevent the device from disconnecting" and "how to **reconnect** with a new token without **disconnecting** the device."
Even the Java code has these two lines right after each other:
```
  client.disconnect();
  client.connect();
```

This disconnect-connect also can be done with the `iot-device-sdk-embedded-c` by calling `[iotc_shutdown_connection](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/include/iotc.h#L432)` and `[iotc_connect](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/include/iotc.h#L252)` API functions.
Please take a look at the [example code](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/examples/common/src/example_utils.c) how it handles the disconnection event in the [on_connection_state_changed](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/examples/common/src/example_utils.c) function and [how the JWT regeneration and re-connection](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/examples/common/src/example_utils.c) is done.

**Comment by lerebel103** [comment]
Thanks for confirming this @atigyi! I thought I had missed something.

Are there any plans to provide a mechanism that does not rely on a "connection reset by peer" to either manually or automatically renew tokens prior to expiry?

**Comment by atigyi** [comment]
Unfortunately there are no plans - I am aware of - for providing in-MQTT-session token renewal.
- HTTP Bridge accepts tokens in every HTTP GET message. So there is no connection reset by peer effect because of token expiry.
- For now the solution for MQTT is to disconnect and reconnect (with a fresh JWT in the MQTT CONNECT message password field). And actually a client may not wait until connection-reset-by-peer happens. The client may trigger disconnect and re-connect immediately before the expected connection drop by server. This will end up in a new MQTT connection, but from higher level point of view one might consider this a continuous device connection.
This is what we have for now.

**Comment by lerebel103** [comment]
Thanks for the feedback.
